let dados = [
    {
        nome: "Hugo Souza",
        descricao: "Revelação das categorias de base do Flamengo, Hugo Souza chegou ao Corinthians em 2024 por empréstimo e rapidamente se adaptou ao estilo de jogo do Timão. Sua segurança sob as traves e importantes defesas o transformaram em peça fundamental da equipe, conquistando a confiança da torcida corintiana. A chegada do jovem goleiro gerou grande expectativa, e sua performance em campo tem confirmado o potencial para se tornar um dos grandes ídolos da posição.",
        insta : "https://www.instagram.com/hugosouza/",
        wiki: "https://pt.wikipedia.org/wiki/Hugo_Souza",
        nacionalidade: "Brasileiro",
        idade: 25,
        camisa: 1,
        posicao: "Goleiro",
        jogos: 14,
        titulos: 0,
        penal_def: 4,
        gols_sofri: 14
    },
    {
        nome: "Rodrigo Garro",
        descricao: "O meia argentino Rodrigo Garro, revelação do futebol argentino, chegou ao Corinthians em 2024 e rapidamente se destacou pela sua habilidade em criar jogadas e distribuir o jogo. Sua adaptação ao futebol brasileiro foi impressionante, tornando-o peça fundamental no meio-campo alvinegro e um dos principais jogadores do Timão.",
        wiki: "https://pt.wikipedia.org/wiki/Rodrigo_Garro",
        insta: "https://www.instagram.com/rodrigarroo/",
        nacionalidade: "Argentino",
        idade: 26,
        camisa: 10,
        posicao: "Meia Esquerda",
        jogos: 44,
        titulos: 0,
        gols: 6,
        assistencias: 5,
    },
    {
        nome: "Ángel Romero",
        descricao: "Ángel Romero, atacante paraguaio, possui uma trajetória marcante no Corinthians. Sua habilidade e garra em campo o tornaram um ídolo da Fiel, contribuindo para diversos títulos e momentos históricos do clube. Com 2 passagens pelo Corinthians, Ángel Romero se destaca como o maiore artilheiro estrangeiro da história do clube, além de ser também o maior artilheiro da Neo Química Arena. Sua importância é inegável, sendo peça fundamental em diversas conquistas alvinegras.",
        insta: "https://www.instagram.com/romeroteam/",
        wiki: "https://pt.wikipedia.org/wiki/%C3%81ngel_Romero_(futebolista)",
        nacionalidade: "Paraguio",
        idade: 32,       
        camisa: 11,
        posicao: "Ponta Esquerda",
        jogos: 306,
        titulos: 4,
        gols: 58,
        assistencias: 24,
    },
    {
        nome: "Yuri Alberto",
        descricao: "Yuri Alberto, atacante brasileiro, chegou ao Corinthians em 2023 e rapidamente se tornou um dos principais jogadores do time. Sua força física, velocidade e habilidade nos dribles o destacam em campo. Com passagens por Internacional e Zenit, Yuri Alberto busca consolidar seu nome na história do Corinthians.",
        insta: "https://www.instagram.com/yurialberto/",
        wiki: "https://pt.wikipedia.org/wiki/Yuri_Alberto_(futebolista)",
        nacionalidade: "Brasileiro",
        idade: 22,
        camisa: 9,
        posicao: "Centroavante",
        jogos: 50,
        titulos: 0,
        gols: 20,
        assistencias: 5,
    },

    {
        nome: "Tales Magno",
        descricao: "Revelado nas categorias de base do Corinthians, Tales Magno é considerado uma das maiores promessas do futebol brasileiro. Com grande potencial técnico e velocidade, o atacante já despertou o interesse de grandes clubes europeus. Atualmente, busca se firmar como titular absoluto na equipe.",
        insta: "https://www.instagram.com/talesmagno/",
        wiki: "https://pt.wikipedia.org/wiki/Tales_Magno_(futebolista)",
        nacionalidade: "Brasileiro",
        idade: 21,
        camisa: 7,
        posicao: "Ponta Direita",
        jogos: 100,
        titulos: 1,
        gols: 15,
        assistencias: 12,
    },
    {
        nome: "Fagner",
        descricao: "Um dos principais líderes do Corinthians, Fagner é lateral-direito e ídolo da torcida. Conhecido por sua raça e entrega em campo, o jogador é um dos mais experientes do elenco. Com diversas passagens pela Seleção Brasileira, Fagner é peça fundamental no esquema tático do Corinthians.",
        insta: "https://www.instagram.com/fagner_corinthians/",
        wiki: "https://pt.wikipedia.org/wiki/Fagner_(futebolista)",
        nacionalidade: "Brasileiro",
        idade: 34,
        camisa: 23,
        posicao: "Lateral-Direito",
        jogos: 450,
        titulos: 6,
        gols: 18,
        assistencias: 50,
    },
];
